#
# Module manifest for module 'AutoCompleteISE'
#
# Generated by: Tore Grøneng @toregroneng tore@firstpoint.no
#
# Generated on: 04.06.2015
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AutoCompleteISE.psm1'

# Version number of this module.
ModuleVersion = '1.0.16.0'

# ID used to uniquely identify this module
GUID = '8d0a04ff-c06c-41b7-b85c-c1b610c5c929'

# Author of this module
Author = 'Tore Grøneng @toregroneng tore@firstpoint.no'

# Company or vendor of this module
CompanyName = 'Firstpoint AS'

# Copyright statement for this module
Copyright = '(c) 2015 Tore Grøneng @toregroneng tore@firstpoint.no. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Add-CurlyBracets', 'Add-DoubleQuotes', 'Add-ElseBlock', 
               'Add-ForeachBlock', 'Add-HereString', 'Add-IfBlock', 
               'Add-ParameterBlock', 'Add-PesterContext', 'Add-PesterItBlock', 
               'Add-RegularParenthesis', 'Add-SingleQuotes', 'Add-SplatBlock', 
               'Add-SquareParenthesis', 'Add-TryBlock', 'Add-TypeLine', 
               'Clear-ISEmenu', 'Enable-AutoCompleteEvent', 
               'Get-AutoCompleteSettings', 'Get-Scriptlevel', 
               'Remove-AutoCompeteEvent', 'Select-CaretLines', 
               'Set-AutoCompleteSettings', 'Set-CaretPosition', 'Switch-Comment'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


